/**
 * Beeminder
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* The HTTP POST schema to create a charge.
*/
export class ChargeRequest {
    /**
    * Username of the user who is getting charged.
    */
    'userId'?: string;
    /**
    * The amount of the charge.
    */
    'amount'?: number;
    /**
    * An optional note describing the charge.
    */
    'note'?: string;
    /**
    * If passed, the Charge is not actually created, but the JSON for it is returned as if it were.
    */
    'dryrun'?: ChargeRequestDryrunEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "userId",
            "baseName": "user_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "number",
            "format": ""
        },
        {
            "name": "note",
            "baseName": "note",
            "type": "string",
            "format": ""
        },
        {
            "name": "dryrun",
            "baseName": "dryrun",
            "type": "ChargeRequestDryrunEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ChargeRequest.attributeTypeMap;
    }

    public constructor() {
    }
}


export type ChargeRequestDryrunEnum = "true" | "false" ;

