/**
 * Beeminder
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class Datapoint {
    /**
    * A unique ID, used to identify a datapoint when deleting or editing it.
    */
    'id'?: string;
    /**
    * The unix time (in seconds) of the datapoint.
    */
    'timestamp'?: number;
    /**
    * The canonical \"data entry format\" of the datapoint.
    */
    'canonical'?: string;
    /**
    * The date of the datapoint. Sometimes timestamps are surprising due to goal deadlines, so if you're looking at Beeminder data, you're probably interested in the daystamp.
    */
    'daystamp'?: string;
    /**
    * The value, e.g., how much you weighed on the day indicated by the timestamp.
    */
    'value'?: number;
    /**
    * An optional comment about the datapoint.
    */
    'comment'?: string;
    /**
    * The unix time that this datapoint was entered or last updated.
    */
    'updatedAt'?: number;
    /**
    * If a datapoint was created via the API and this parameter was included, it will be echoed back.
    */
    'requestid'?: string;
    /**
    * Parameter for datapoint representation in goals
    */
    'origin'?: string;
    'fulltext'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "timestamp",
            "baseName": "timestamp",
            "type": "number",
            "format": ""
        },
        {
            "name": "canonical",
            "baseName": "canonical",
            "type": "string",
            "format": ""
        },
        {
            "name": "daystamp",
            "baseName": "daystamp",
            "type": "string",
            "format": ""
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "number",
            "format": ""
        },
        {
            "name": "comment",
            "baseName": "comment",
            "type": "string",
            "format": ""
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "number",
            "format": ""
        },
        {
            "name": "requestid",
            "baseName": "requestid",
            "type": "string",
            "format": ""
        },
        {
            "name": "origin",
            "baseName": "origin",
            "type": "string",
            "format": ""
        },
        {
            "name": "fulltext",
            "baseName": "fulltext",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Datapoint.attributeTypeMap;
    }

    public constructor() {
    }
}

