/**
 * Beeminder
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class GoalDuebyValue {
    'delta'?: number;
    'total'?: number;
    'formattedDeltaForBeedroid'?: string;
    'formattedTotalForBeedroid'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "delta",
            "baseName": "delta",
            "type": "number",
            "format": ""
        },
        {
            "name": "total",
            "baseName": "total",
            "type": "number",
            "format": ""
        },
        {
            "name": "formattedDeltaForBeedroid",
            "baseName": "formatted_delta_for_beedroid",
            "type": "string",
            "format": ""
        },
        {
            "name": "formattedTotalForBeedroid",
            "baseName": "formatted_total_for_beedroid",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GoalDuebyValue.attributeTypeMap;
    }

    public constructor() {
    }
}

