/**
 * Beeminder
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class GoalUpdateRequest {
    'title'?: string;
    'yaxis'?: string;
    'tmin'?: string;
    'tmax'?: string;
    'secret'?: boolean;
    'datapublic'?: boolean;
    /**
    * Like road but with an additional initial row consisting of [initday, initval, null] and an additional final row consisting of [goaldate, goalval, rate]
    */
    'roadall'?: Array<Array<number>>;
    /**
    * one of {\"api\", \"ifttt\", \"zapier\", or clientname}. Default: none (i.e., \"manual\").
    */
    'datasource'?: string;
    'tags'?: Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "title",
            "baseName": "title",
            "type": "string",
            "format": ""
        },
        {
            "name": "yaxis",
            "baseName": "yaxis",
            "type": "string",
            "format": ""
        },
        {
            "name": "tmin",
            "baseName": "tmin",
            "type": "string",
            "format": ""
        },
        {
            "name": "tmax",
            "baseName": "tmax",
            "type": "string",
            "format": ""
        },
        {
            "name": "secret",
            "baseName": "secret",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "datapublic",
            "baseName": "datapublic",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "roadall",
            "baseName": "roadall",
            "type": "Array<Array<number>>",
            "format": ""
        },
        {
            "name": "datasource",
            "baseName": "datasource",
            "type": "string",
            "format": ""
        },
        {
            "name": "tags",
            "baseName": "tags",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GoalUpdateRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

