/**
 * Beeminder
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Exactly two out of three of goaldate, goalval, and rate are required.
*/
export class GoalCreateRequest {
    /**
    * The final part of the URL of the goal, used as an identifier.
    */
    'slug'?: string;
    'title'?: string;
    'goalType'?: GoalCreateRequestGoalTypeEnum;
    /**
    * Goal units, like \"hours\" or \"pushups\" or \"pages\".
    */
    'gunits'?: string;
    /**
    * The end date (unix timestamp) of the goal.
    */
    'goaldate'?: number;
    /**
    * The number the bright red line will eventually reach.
    */
    'goalval'?: number;
    /**
    * The slope of the (final section of the) bright red line in runits.
    */
    'rate'?: number;
    /**
    * The y-value of the start of the bright red line.
    */
    'initval'?: number;
    /**
    * Whether you have to be logged in as owner of the goal to view it.
    */
    'secret'?: boolean;
    /**
    * Whether you have to be logged in as the owner of the goal to view the datapoints
    */
    'datapublic'?: boolean;
    /**
    * one of {\"api\", \"ifttt\", \"zapier\", or clientname}. Default: none (i.e., \"manual\").
    */
    'datasource'?: string;
    /**
    * Pass this to test the endpoint without actually creating a goal. Defaults to false.
    */
    'dryrun'?: boolean;
    'tags'?: Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "slug",
            "baseName": "slug",
            "type": "string",
            "format": ""
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string",
            "format": ""
        },
        {
            "name": "goalType",
            "baseName": "goal_type",
            "type": "GoalCreateRequestGoalTypeEnum",
            "format": ""
        },
        {
            "name": "gunits",
            "baseName": "gunits",
            "type": "string",
            "format": ""
        },
        {
            "name": "goaldate",
            "baseName": "goaldate",
            "type": "number",
            "format": ""
        },
        {
            "name": "goalval",
            "baseName": "goalval",
            "type": "number",
            "format": ""
        },
        {
            "name": "rate",
            "baseName": "rate",
            "type": "number",
            "format": ""
        },
        {
            "name": "initval",
            "baseName": "initval",
            "type": "number",
            "format": ""
        },
        {
            "name": "secret",
            "baseName": "secret",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "datapublic",
            "baseName": "datapublic",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "datasource",
            "baseName": "datasource",
            "type": "string",
            "format": ""
        },
        {
            "name": "dryrun",
            "baseName": "dryrun",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "tags",
            "baseName": "tags",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GoalCreateRequest.attributeTypeMap;
    }

    public constructor() {
    }
}


export type GoalCreateRequestGoalTypeEnum = "hustler" | "biker" | "fatloser" | "gainer" | "inboxer" | "drinker" | "custom" ;

