/*
Beeminder

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
Contact: austinrossely@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// BigUserDeletedGoalsInner struct for BigUserDeletedGoalsInner
type BigUserDeletedGoalsInner struct {
	Id *string `json:"id,omitempty"`
}

// NewBigUserDeletedGoalsInner instantiates a new BigUserDeletedGoalsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBigUserDeletedGoalsInner() *BigUserDeletedGoalsInner {
	this := BigUserDeletedGoalsInner{}
	return &this
}

// NewBigUserDeletedGoalsInnerWithDefaults instantiates a new BigUserDeletedGoalsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBigUserDeletedGoalsInnerWithDefaults() *BigUserDeletedGoalsInner {
	this := BigUserDeletedGoalsInner{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *BigUserDeletedGoalsInner) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BigUserDeletedGoalsInner) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *BigUserDeletedGoalsInner) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *BigUserDeletedGoalsInner) SetId(v string) {
	o.Id = &v
}

func (o BigUserDeletedGoalsInner) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	return json.Marshal(toSerialize)
}

type NullableBigUserDeletedGoalsInner struct {
	value *BigUserDeletedGoalsInner
	isSet bool
}

func (v NullableBigUserDeletedGoalsInner) Get() *BigUserDeletedGoalsInner {
	return v.value
}

func (v *NullableBigUserDeletedGoalsInner) Set(val *BigUserDeletedGoalsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableBigUserDeletedGoalsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableBigUserDeletedGoalsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBigUserDeletedGoalsInner(val *BigUserDeletedGoalsInner) *NullableBigUserDeletedGoalsInner {
	return &NullableBigUserDeletedGoalsInner{value: val, isSet: true}
}

func (v NullableBigUserDeletedGoalsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBigUserDeletedGoalsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


